/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package de.hx.bokumsatzkontroller;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int AliceBlue=0x7f05002c;
        public static final int AntiqueWhite=0x7f050022;
        public static final int Aqua=0x7f05007c;
        public static final int Aquamarine=0x7f050061;
        public static final int Azure=0x7f05002a;
        public static final int Beige=0x7f050027;
        public static final int Bisque=0x7f05000d;
        public static final int Black=0x7f05008b;
        public static final int BlanchedAlmond=0x7f05000b;
        public static final int Blue=0x7f050087;
        public static final int BlueViolet=0x7f05005a;
        public static final int Brown=0x7f05004e;
        public static final int BurlyWood=0x7f050034;
        public static final int CadetBlue=0x7f05006c;
        public static final int Chartreuse=0x7f050062;
        public static final int Chocolate=0x7f05003e;
        public static final int Coral=0x7f050017;
        public static final int CornflowerBlue=0x7f05006b;
        public static final int Cornsilk=0x7f050007;
        public static final int Crimson=0x7f050037;
        public static final int Cyan=0x7f05007d;
        public static final int DarkBlue=0x7f050089;
        public static final int DarkCyan=0x7f050083;
        public static final int DarkGoldenrod=0x7f050046;
        public static final int DarkGray=0x7f05004d;
        public static final int DarkGreen=0x7f050086;
        public static final int DarkKhaki=0x7f050043;
        public static final int DarkMagenta=0x7f050058;
        public static final int DarkOliveGreen=0x7f05006d;
        public static final int DarkOrange=0x7f050016;
        public static final int DarkOrchid=0x7f050051;
        public static final int DarkRed=0x7f050059;
        public static final int DarkSalmon=0x7f050031;
        public static final int DarkSeaGreen=0x7f050056;
        public static final int DarkSlateBlue=0x7f050070;
        public static final int DarkSlateGray=0x7f050076;
        public static final int DarkTurquoise=0x7f050081;
        public static final int DarkViolet=0x7f050053;
        public static final int DeepPink=0x7f05001b;
        public static final int DeepSkyBlue=0x7f050082;
        public static final int DimGray=0x7f050069;
        public static final int DodgerBlue=0x7f05007a;
        public static final int FireBrick=0x7f050047;
        public static final int FloralWhite=0x7f050005;
        public static final int ForestGreen=0x7f050078;
        public static final int Fuchsia=0x7f05001c;
        public static final int Gainsboro=0x7f050036;
        public static final int GhostWhite=0x7f050024;
        public static final int Gold=0x7f050011;
        public static final int Goldenrod=0x7f050039;
        public static final int Gray=0x7f05005d;
        public static final int Green=0x7f050085;
        public static final int GreenYellow=0x7f05004b;
        public static final int Honeydew=0x7f05002b;
        public static final int HotPink=0x7f050018;
        public static final int IndianRed=0x7f050040;
        public static final int Indigo=0x7f05006e;
        public static final int Ivory=0x7f050001;
        public static final int Khaki=0x7f05002d;
        public static final int Lavender=0x7f050032;
        public static final int LavenderBlush=0x7f050009;
        public static final int LawnGreen=0x7f050063;
        public static final int LemonChiffon=0x7f050006;
        public static final int LightBlue=0x7f05004c;
        public static final int LightCoral=0x7f05002e;
        public static final int LightCyan=0x7f050033;
        public static final int LightGoldenrodYellow=0x7f050020;
        public static final int LightGreen=0x7f050055;
        public static final int LightGrey=0x7f05003c;
        public static final int LightPink=0x7f050013;
        public static final int LightSalmon=0x7f050015;
        public static final int LightSeaGreen=0x7f050079;
        public static final int LightSkyBlue=0x7f05005b;
        public static final int LightSlateGray=0x7f050065;
        public static final int LightSteelBlue=0x7f050049;
        public static final int LightYellow=0x7f050002;
        public static final int Lime=0x7f05007f;
        public static final int LimeGreen=0x7f050075;
        public static final int Linen=0x7f050021;
        public static final int Magenta=0x7f05001d;
        public static final int Maroon=0x7f050060;
        public static final int MediumAquamarine=0x7f05006a;
        public static final int MediumBlue=0x7f050088;
        public static final int MediumOrchid=0x7f050045;
        public static final int MediumPurple=0x7f050054;
        public static final int MediumSeaGreen=0x7f050074;
        public static final int MediumSlateBlue=0x7f050064;
        public static final int MediumSpringGreen=0x7f050080;
        public static final int MediumTurquoise=0x7f05006f;
        public static final int MediumVioletRed=0x7f050041;
        public static final int MidnightBlue=0x7f05007b;
        public static final int MintCream=0x7f050025;
        public static final int MistyRose=0x7f05000c;
        public static final int Moccasin=0x7f05000e;
        public static final int NavajoWhite=0x7f05000f;
        public static final int Navy=0x7f05008a;
        public static final int OldLace=0x7f05001f;
        public static final int Olive=0x7f05005e;
        public static final int OliveDrab=0x7f050067;
        public static final int Orange=0x7f050014;
        public static final int OrangeRed=0x7f05001a;
        public static final int Orchid=0x7f05003a;
        public static final int PaleGoldenrod=0x7f05002f;
        public static final int PaleGreen=0x7f050052;
        public static final int PaleTurquoise=0x7f05004a;
        public static final int PaleVioletRed=0x7f050038;
        public static final int PapayaWhip=0x7f05000a;
        public static final int PeachPuff=0x7f050010;
        public static final int Peru=0x7f05003f;
        public static final int Pink=0x7f050012;
        public static final int Plum=0x7f050035;
        public static final int PowderBlue=0x7f050048;
        public static final int Purple=0x7f05005f;
        public static final int Red=0x7f05001e;
        public static final int RosyBrown=0x7f050044;
        public static final int RoyalBlue=0x7f050072;
        public static final int SaddleBrown=0x7f050057;
        public static final int Salmon=0x7f050023;
        public static final int SandyBrown=0x7f050029;
        public static final int SeaGreen=0x7f050077;
        public static final int Seashell=0x7f050008;
        public static final int Sienna=0x7f05004f;
        public static final int Silver=0x7f050042;
        public static final int SkyBlue=0x7f05005c;
        public static final int SlateBlue=0x7f050068;
        public static final int SlateGray=0x7f050066;
        public static final int Snow=0x7f050004;
        public static final int SpringGreen=0x7f05007e;
        public static final int SteelBlue=0x7f050071;
        public static final int Tan=0x7f05003d;
        public static final int Teal=0x7f050084;
        public static final int Thistle=0x7f05003b;
        public static final int Tomato=0x7f050019;
        public static final int Turquoise=0x7f050073;
        public static final int Violet=0x7f050030;
        public static final int Wheat=0x7f050028;
        public static final int White=0x7f050000;
        public static final int WhiteSmoke=0x7f050026;
        public static final int Yellow=0x7f050003;
        public static final int YellowGreen=0x7f050050;
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.
    
         */
        public static final int activity_horizontal_margin=0x7f060000;
        public static final int activity_vertical_margin=0x7f060001;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id {
        public static final int TableLayout1=0x7f0a0000;
        public static final int TextView06=0x7f0a0015;
        public static final int TextView11=0x7f0a001e;
        public static final int TextView18=0x7f0a0027;
        public static final int TextView25=0x7f0a0030;
        public static final int TextView32=0x7f0a0039;
        public static final int TextView39=0x7f0a0042;
        public static final int TextView46=0x7f0a004b;
        public static final int action_settings=0x7f0a005b;
        public static final int ente=0x7f0a000b;
        public static final int enteBetellEditText=0x7f0a000d;
        public static final int enteEinkaufTotal=0x7f0a0012;
        public static final int enteEinkaufspreis=0x7f0a0011;
        public static final int enteNettoPreis=0x7f0a000f;
        public static final int enteNettoUmsatz=0x7f0a0010;
        public static final int enteTableRow=0x7f0a000a;
        public static final int enteTotal=0x7f0a000e;
        public static final int entebrustfilet=0x7f0a004a;
        public static final int entebrustfiletBetellEditText=0x7f0a004c;
        public static final int entebrustfiletEinkaufTotal=0x7f0a0051;
        public static final int entebrustfiletEinkaufspreis=0x7f0a0050;
        public static final int entebrustfiletNettoPreis=0x7f0a004e;
        public static final int entebrustfiletNettoUmsatz=0x7f0a004f;
        public static final int entebrustfiletTableRow07=0x7f0a0049;
        public static final int entebrustfiletTotal=0x7f0a004d;
        public static final int garnelen=0x7f0a0041;
        public static final int garnelenEinkaufTotal=0x7f0a0048;
        public static final int garnelenEinkaufspreis=0x7f0a0047;
        public static final int garnelenNettoPreis=0x7f0a0045;
        public static final int garnelenNettoUmsatz=0x7f0a0046;
        public static final int garnelenTableRow=0x7f0a0040;
        public static final int garnelenTotal=0x7f0a0044;
        public static final int gernelenBetellEditText=0x7f0a0043;
        public static final int haehnchenbrust=0x7f0a0014;
        public static final int haehnchenbrustBetellEditText=0x7f0a0016;
        public static final int haehnchenbrustEinkaufTotal=0x7f0a001b;
        public static final int haehnchenbrustEinkaufspreis=0x7f0a001a;
        public static final int haehnchenbrustNettoPreis=0x7f0a0018;
        public static final int haehnchenbrustNettoUmsatz=0x7f0a0019;
        public static final int haehnchenbrustTableRow0=0x7f0a0013;
        public static final int haehnchenbrustTotal=0x7f0a0017;
        public static final int haehnchenkeule=0x7f0a002f;
        public static final int haehnchenkeuleBetellEditText=0x7f0a0031;
        public static final int haehnchenkeuleEinkaufTotal=0x7f0a0036;
        public static final int haehnchenkeuleEinkaufspreis=0x7f0a0035;
        public static final int haehnchenkeuleNettoPreis=0x7f0a0033;
        public static final int haehnchenkeuleNettoUmsatz=0x7f0a0034;
        public static final int haehnchenkeuleTableRow=0x7f0a002e;
        public static final int haehnchenkeuleTotal=0x7f0a0032;
        public static final int lamm=0x7f0a0038;
        public static final int lammBetellEditText=0x7f0a003a;
        public static final int lammEinkaufTotal=0x7f0a003f;
        public static final int lammEinkaufspreis=0x7f0a003e;
        public static final int lammNettoPreis=0x7f0a003c;
        public static final int lammNettoUmsatz=0x7f0a003d;
        public static final int lammTableRow=0x7f0a0037;
        public static final int lammTotal=0x7f0a003b;
        public static final int rinderoberschaleTableRow=0x7f0a0025;
        public static final int rindoberschale=0x7f0a0026;
        public static final int rindoberschaleBetellEditText=0x7f0a0028;
        public static final int rindoberschaleEinkaufTotal=0x7f0a002d;
        public static final int rindoberschaleEinkaufspreis=0x7f0a002c;
        public static final int rindoberschaleNettoPreis=0x7f0a002a;
        public static final int rindoberschaleNettoUmsatz=0x7f0a002b;
        public static final int rindoberschaleTotal=0x7f0a0029;
        public static final int seelachfiletTableRow=0x7f0a001c;
        public static final int seelachsfilet=0x7f0a001d;
        public static final int seelachsfiletBetellEditText=0x7f0a001f;
        public static final int seelachsfiletEinkaufTotal=0x7f0a0024;
        public static final int seelachsfiletEinkaufspreis=0x7f0a0023;
        public static final int seelachsfiletNettoPreis=0x7f0a0021;
        public static final int seelachsfiletNettoUmsatz=0x7f0a0022;
        public static final int seelachsfiletTotal=0x7f0a0020;
        public static final int summeEinkaufTotal=0x7f0a005a;
        public static final int summeNettoUmsatz=0x7f0a0058;
        public static final int tableRow1=0x7f0a0001;
        public static final int tableRow2=0x7f0a0052;
        public static final int textView1=0x7f0a0002;
        public static final int textView14=0x7f0a0006;
        public static final int textView2=0x7f0a0008;
        public static final int textView3=0x7f0a0003;
        public static final int textView4=0x7f0a0004;
        public static final int textView49=0x7f0a0053;
        public static final int textView5=0x7f0a0005;
        public static final int textView50=0x7f0a0054;
        public static final int textView51=0x7f0a0055;
        public static final int textView52=0x7f0a0056;
        public static final int textView53=0x7f0a0057;
        public static final int textView55=0x7f0a0059;
        public static final int textView6=0x7f0a0007;
        public static final int textView7=0x7f0a0009;
        public static final int textView9=0x7f0a000c;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
    }
    public static final class menu {
        public static final int main=0x7f090000;
    }
    public static final class string {
        public static final int action_settings=0x7f070001;
        public static final int app_name=0x7f070000;
        public static final int hello_world=0x7f070002;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f080000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f080001;
    }
    public static final class xml {
        public static final int fleisch=0x7f040000;
    }
}
